#服务器配置
server:
  #端口
  port: 9090

#服务器发现注册配置
eureka:
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:8070/eureka

#spring配置
spring:
  #应用配置
  application:
    #名称: 认证授权服务
    name: certification-server
  thymeleaf:
    #关闭thymeleaf缓存
    cache: false
  datasource:
    name: local
    url: jdbc:mysql://127.0.0.1:3306/certification?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

#mybatis配置
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.xiaoxin.certification.dao.*Mapper