# server
server:
  port: 9090

# register
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

# spring
spring:
  application:
    name: certification-server
  thymeleaf:
    cache: false
  datasource:
    name: local
    url: jdbc:mysql://localhost:3306/certification?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
  redis:
    host: 127.0.0.1
    port: 6379

# db-operation
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.xiaoxin.certification.dao.*Mapper

# log
logging:
  config: classpath:logback-spring.xml
  path: ../certification-server/logs/

# github
github:
  clientId: 55faa83726f98252c50e
  secret: 7b030111dcc88c652d045be5c599dcd661ac9aa7
  auth-url: /auth/github

# application
application:
  url: http://localhost:9090/
