server:
  port: 8882
  servlet:
    context-path: /client
  session:
    cookie:
      name: SESSION1
security:
  auth-server: http://localhost:9090
  oauth2:
    client:
      clientId: certification
      clientSecret: 123456
      accessTokenUri: ${security.auth-server}/oauth/token
      userAuthorizationUri: ${security.auth-server}/oauth/authorize
      scope: read
    resource:
      userInfoUri: ${security.auth-server}/user
spring:
  thymeleaf:
    cache: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.74.128:8070/eureka

logging:
  config: classpath:logback-spring.xml
  path: ../client/logs/